name: mobx13
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_mobx: ^1.1.0
  get_it: ^4.0.2
  intl: ^0.16.1
  numberpicker: ^1.2.0
  shared_preferences: ^0.5.7+1
  clippy_flutter: ^1.1.1
  mobx: ^1.1.1
  dialog_information_to_specific_platform: ^0.0.4

dev_dependencies:
  build_runner: ^1.9.0
  mobx_codegen: ^1.0.3
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/launchscreen.png
  color: "FDC149"

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/launchscreen.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/home/
    - assets/images/produtos/
