name: mobx05video52
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^1.1.0
  intl: ^0.16.1
  numberpicker: ^1.2.0
  get_it: ^4.0.2
  clippy_flutter: ^1.1.1
  shared_preferences: ^0.5.7+3

dev_dependencies:
  build_runner: ^1.9.0
  mobx_codegen: ^1.0.3

flutter:
  uses-material-design: true
  #Registro para acesso a pasta assets/images/home/
  assets:
    - assets/images/home/
    - assets/images/produtos/